module BCDD::Contract
  class Config
    include ::Singleton

    attr_accessor proxy_enabled: bool
    attr_accessor assertions_enabled: bool

    def self.instance: () -> Config

    def initialize: () -> void

    def options: () -> Hash[Symbol, bool]
  end
end
