module BCDD::Contract::Interface
  module Callbacks
    def self.included: (untyped) -> void
    def self.extended: (untyped) -> void
  end

  def self.included: (untyped) -> void

  module AlwaysEnabled
    def self.included: (untyped) -> void
  end
end
