module BCDD::Contract
  class Proxy
    attr_reader object: untyped

    def self.new: (untyped) -> Proxy

    def self.to_proc: () -> Proc

    def initialize: (untyped) -> Proxy
  end

  def self.config: () -> Config
  def self.configuration: { (Config) -> void } -> Config
end
