module BCDD::Contract
  module Core
    class Proxy
      attr_reader object: untyped

      def self.new: (untyped) -> Proxy

      def self.to_proc: () -> Proc

      def initialize: (untyped) -> Proxy
    end
  end
end
